version: '3.9'

services:
  go-app:
    container_name: notes-taking-application-app
    image: notes-taking-application
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}